#!/bin/sh -l

pip install --user -r requirements.txt

# install requirements.txt if it exists
cd docs

make clean

make confluence \
  SPHINXOPTS="-D confluence_server_user=$INPUT_USERNAME -D confluence_server_pass=$INPUT_APITOKEN"
